export { default as Background_slot } from './Background.png';
export { default as Banner_slot } from './Banner.png';
export { default as Blank_slot } from './Blank.png';
export { default as Bronze_EOS } from './Bronze EOS.png';
export { default as Bronze_Planet } from './Bronze Planet.png';
export { default as Dial_Frame } from './Dial Frame.png';
export { default as Gold_EOS } from './Gold EOS.png';
export { default as Gold_Planet } from './Gold Planet.png';
export { default as Paytable_slot } from './Paytable.png';
export { default as Place_Bets } from './Place Bets.png';
export { default as Silver_EOS } from './Silver EOS.png';
export { default as Silver_Planet } from './Silver Planet.png';
